services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn fastapi_sourcemod_admins.main:app --reload --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - ./:/app/
    env_file:
      - .env
    restart: always
    networks:
      - shark

networks:
  shark:
    name: shark
    external: true